app/views/auth.py
import os
import random
import string

from datetime import datetime, date
from app import app, login_manager
from sqlalchemy import exc

from flask import (
    render_template, request, redirect, url_for, Blueprint, flash
)
from flask_login import (
    login_user, logout_user, current_user, login_required, fresh_login_required
)

from app.logging import logger, logg_error
from app.mail import send_mail
from app.oauth import OAuthSignIn
from app.models import (
    SessionContext, IntegrityError, User, Company, Access, OAuth_User, Error
)
from app.decorators import (
    validate_login, validate_registration, validate_provider,
    is_logged_in, requires_roles
)

mod = Blueprint('auth', __name__)


@mod.route('/login', methods=['GET', 'POST'])
@is_logged_in
@validate_login
def login():
    """ Loggs user in, if user exists this redirects to index
        otherwise it redirects back to login """

    if request.method == 'GET':
        return render_template("auth/login.html")

    with SessionContext(commit=True) as session:
        try:
            registerd_user = session.query(User)\
                                    .filter_by(email=request.form['email'])\
                                    .first()

            # If user does not exist, redirect to login with status message.
            if not registerd_user:
                logger.login_failed_user(request.form.get('email'))
                logg_error(location="login", error="Logged in with email that does not exist in database, {email}".format(email=request.form.get('email')), warning=True)
                return render_template("auth/login.html", status='user_does_not_exist')

            # If user password is incorrect, redirect to login with status message
            if not registerd_user.check_password(password=request.form.get('password')):
                logger.login_failed_password(request.form.get('email'))
                logg_error(location="login", error="Logged in with incorrect password {email}".format(email=request.form.get('email')), warning=True)
                return render_template("auth/login.html", status='wrong_password')

            remember_me = request.form.get('remember_me') is not None
            login_user(registerd_user, remember=remember_me)
            logger.login_successful(request.form.get('email'))
        except Exception as e:
            session.rollback()
            logg_error(location='login', error=str(e))
            return redirect(url_for('main.index'))

        return redirect(url_for('main.index'))


@mod.route('/register', methods=['GET', 'POST'])
@is_logged_in
@validate_registration
def register():
    """ Registers a user.
        Redirects to login """

    if request.method == 'GET':
        return render_template("auth/register.html")

    with SessionContext() as session:
        try:
            user = User(name=request.form['name'],
                        password=request.form['password'],
                        company=request.form['company'],
                        email=request.form['email'])

            session.add(user)
            session.commit()
        except exc.IntegrityError as e:
            session.rollback()
            logger.register_failed(request.form.get('email'))
            logg_error(location='register', error="Tried to register with email that already exists in database {email}".format(email=request.form.get('email')), warning=True)
            return render_template("auth/register.html",
                                   status='user_already_exists')
        except Exception as e:
            sesison.rollback()
            logg_error(location='register', error=str(e))
            return render_template("auth/register.html",
                                   status='error in registry')

        company = session.query(Company).filter_by(name='Fuglar').first()
        access = Access(user_id=user.id, company_id=company.id)
        session.add(access)
        session.commit()

        logger.register_successful(request.form.get('email'))
        send_mail(request.form['email'])
        login_user(user, remember=False)
        return redirect(url_for('auth.login'))


@mod.route('/authorize/<provider>')
@validate_provider
def oauth_authorize(provider):
    """ Used to call login provider """
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@mod.route('/callback/<provider>')
@validate_provider
def oauth_callback(provider):
    """ Loggs in a user if he exists, else it tries to register the user.
        Allways redirects to index """

    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))

    oauth = OAuthSignIn.get_provider(provider)
    id, email, name = oauth.callback()
    if email is None:
        logg_error(location='oauth_callback-{provider}'.format(provider=provider), error="No email supplied from provider, id: {id}, name: {name}".format(id=id, name=name))
        return redirect(url_for('main.index'))

    with SessionContext() as session:

        if provider == 'facebook':
            oauth_user = session.query(OAuth_User)\
                                .filter_by(provider_id=id, provider=provider)\
                                .first()
        else:
            oauth_user = session.query(OAuth_User)\
                                .filter_by(email=email, provider=provider)\
                                .first()


        print(oauth_user)

        if not oauth_user:
            try:
                objs = list()
                user = User(name=name,
                            password=''.join(random.choice(string.ascii_uppercase + string.digits + " ") for _ in range(100)),
                            company='',
                            email=email)
                session.add(user)
                session.commit()
                objs.append(user)
                oUser = OAuth_User(provider_id=id,
                                   user_id=user.get_id(),
                                   provider=provider,
                                   email=email)
                session.add(oUser)
                session.commit()
                objs.append(oUser)
                send_mail(id)
                logger.oauth_register_successful(email)

                company = session.query(Company).filter_by(name='Fuglar').first()
                access = Access(user_id=user.id, company_id=company.id)
                session.add(access)
                session.commit()
                objs.append(access)


            except Exception as e:
                logger.oauth_register_failed(email)
                session.rollback()
                logg_error(location='oauth_callback-{provider}'.format(provider=provider), error=str(e))
                try:
                    for ob in objs[::-1]:
                        session.delete(ob)
                        session.commit()
                except UnboundLocalError:
                    pass
                return redirect(url_for('main.index'))
        else:
            user = session.query(User).filter_by(id=oauth_user.user_id).first()
            logger.oauth_login_successful(email)


        login_user(user, remember=True)
        return redirect(url_for('main.index'))

'''
@app.route("/reauthenticate", methods=["GET", "POST"])
@login_required
def reauth():
    # if the session is `fresh` just redirect to the page the user has requested
    if not login_fresh():
        form = LoginForm()
        if form.validate_on_submit():
            # do password check here
            confirm_login()
            return redirect(url_for("index"))
        return render_template("reauth.html", form=form)
    return redirect(request.args.get("next") or url_for("index"))
'''


@mod.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))



@mod.route('/change_password', methods=['POST'])
@login_manager.needs_refresh_handler
def change_password():


    pw = request.form['pw']
    pw1 = request.form['pw1']
    pw2 = request.form['pw2']

    if pw1 != pw2:
        flash("Ný lykilorð passa ekki")
        return redirect(url_for('main.profile'))


    with SessionContext() as session:
        user = session.query(User)\
            .filter_by(id = current_user.id)\
            .first()

        if not user.check_password(pw):
            flash("Rangt lykilorð")
            return redirect(url_for('main.profile'))


        user.update_password(pw1)
        session.add(user)
        session.commit()  

        return redirect(url_for('main.index'))





""" REMEMBER
have
@login_manager.needs_refresh_handler
decorator in actions that are sensitive, like changing password
"""

app/views/main.py
import os
import random
import string
import json

from datetime import datetime, date

from sqlalchemy import exc

from flask import (
    render_template, request, redirect, url_for, Blueprint, session as flask_session
)
from flask_login import (
    login_user, logout_user, current_user, login_required, fresh_login_required
)

from app import app
from app.logging import logger, logg_error
from app.mail import send_mail
from app.oauth import OAuthSignIn
from app.models import (
    SessionContext, IntegrityError, User, Company, Access, OAuth_User, Error,
    QueryUsers, QueryErrorWarning, QueryError, QueryGolfCourses, QueryGolfCards,
    GolfCourseAccess, GolfCourse, QueryNumberOfCardsLeft, 
    QueryStatisticsCardsUsed, QueryStatisticsCardsUsedByUser
)
from app.decorators import (
    validate_login, validate_registration, validate_provider,
    is_logged_in, requires_roles
)


mod = Blueprint('main', __name__)


@mod.context_processor
def utility_processor():
    qCL = QueryNumberOfCardsLeft()

    with SessionContext() as session:
        try:
            cards_left = qCL.scalar(session=session, user_id=current_user.id, year='2018')
            if cards_left < 0:
                cards_left = 0
            access = session.query(Access).filter_by(user_id=current_user.id).all()

            if access:
                companies = session.query(Company).filter(Company.id.in_([a.company_id for a in access])).all()
            else:
                companies = None
        except AttributeError as e:
            # AttributeError is catched if current_user is not defined.
            print(str(e))
            companies = None
            cards_left = None

        return dict(companies=companies, cards_left=cards_left)


@mod.route('/')
@login_required
def index():
    return render_template("main/index.html")


@mod.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():

    # If request is GET, serve template for profile, otherwise its POST request
    if request.method == 'GET':
        return render_template("main/profile.html")

    with SessionContext() as session:
        try:
            user = session.query(User).filter_by(id=current_user.id).first()

            if request.form.get('company'):
                user.company = request.form.get('company')

            if request.form.get("displayname"):
                user.displayname = request.form.get("displayname")[:10]

            # Add and commit this user changes to database.
            session.add(user)
            session.commit()

        except Exception as e:
            session.rollback()
            # Logg error to database
            logg_error(location='profile', error=str(e))

    return redirect(url_for('main.profile'))


@mod.route('/statistics')
@login_required
@requires_roles('admin', 'staff')
def statistics():

    with SessionContext() as session:

        year = request.args.get('year', date.today().year)

        today = date(int(year), 1, 1)

        qSCU = QueryStatisticsCardsUsed()
        qSCUbU = QueryStatisticsCardsUsedByUser()

        cardsused = [_ for _ in qSCU.execute(session=session, date=today)]
        cardsused_byuser = [_ for _ in qSCUbU.execute(session=session, date=today)]


        return render_template("main/statistics.html", cardsused = json.dumps(cardsused), cardsused_byuser = json.dumps(cardsused_byuser), year = year)


@mod.route('/c/<name>')
@login_required
@requires_roles('admin')
def company(name):
    with SessionContext() as session:

        flask_session['url_admin_page'] = url_for(request.endpoint, name=name)

        company = session.query(Company).filter_by(name=name).first()
        access = session.query(Access).filter_by(user_id=current_user.id)\
            .filter_by(company_id=company.id).first()

        if not access:
            return redirect(url_for("main.index"))

        qU = QueryUsers()
        qEW = QueryErrorWarning()
        qE = QueryError()
        qGC = QueryGolfCourses()
        qGCa = QueryGolfCards()

        return render_template("main/company.html",
            users=qU.execute(session=session),
            errorswarning=qEW.execute(session=session),
            errors=qE.execute(session=session),
            golfcourses=qGC.execute(session=session, company_id=company.id),
            golfcards=qGCa.execute(session=session, company_id=company.id),
            path=name)

app/templates/main/_base.html
{% extends "_base.html" %}
{% block content %}

{% include "main/_sidebar.html" %}
<div class="main-panel">

    {% include "_topbar.html" %}

    <div class="content">
        <div class="container-fluid">
            {% block main %}{% endblock %}
        </div>
    </div>

    {% include "_footer.html" %}

</div>

{% endblock %}

{% block modals %}

{% include "main/_modals.html" %}

{% endblock %}

app/templates/main/_modals.html
{% block _modals %}

<div class="modal fade" id="cardsleft" role="dialog">
  <div class="modal-dialog">
    <div class="card card-modal">
      <div class="content">
          <div class="row">
            <div class="text-center" id="cardsleft-date" value="">
              <h4 id="cardsleft-date-h4"></h4>
            </div>
          </div>
          <div class="row">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                  <div class="text-center card-show">

                      <ul id="cards-availible">

                      </ul>
                      <ul id="cards-notavailible" style="display: none;">
                        {% if cards_left > 0 %}
                          <p>Engin kort aðgengileg.</p>
                          <p>Ef þú ert þegar skráð/ur fyrir kortum, þá getur þú ekki skráð þig á annan dag fyrr en hin kortin hafa verið notuð.</p>
                          <p>Þú getur þó alltaf tekið frá kort á líðandi degi.</p>
                        {% else %}
                          <p>Engin kort aðgengileg.</p>
                          <p>Þú ert komin(n) yfir hámarksfjölda leyfilegra skráninga ársins og getur því ekki skráð kort fram í tímann. Þú getur þó enn tekið frá kort á líðandi degi. Gleðilegt golfsumar.</p>
                        {% endif %}
                      </ul>
                  </div>
              </div>
          </div>
          <div class="row">
              <div class="col-xs-12">
                  <hr />
                  <div class="text-center">
                    <button type="submit" id="send-availible" class="btn btn-success btn-fill btn-wd btn-clean">Taka frá</button>
                    <button type="submit" onclick="$('#cardsleft').modal('toggle');" class="btn btn-warning btn-fill btn-wd btn-clean">Loka</button>
                  </div>
              </div>
          </div>
        </div>
    </div>
  </div>
</div>

<div class="modal fade" id="cardinfo" role="dialog">
  <div class="modal-dialog">
    <div class="card card-modal">
      <div class="content">
          <div class="row">
            <div class="text-center">
            </div>
          </div>
          <div class="row">
              <div class="col-xs-12 col-md-offset-3 col-md-6">
                  <div class="text-center card-show" id="cardinfo-id">
                      <h5 id="cardinfo-coursename"></h5>
                      <h5 id="cardinfo-date"></h5>
                      <h5 id="cardinfo-username"></h5>
                      <h5 id="cardinfo-number"></h5>
                  </div>
              </div>
          </div>
          <div class="row">
              <div class="col-xs-12">
                  <hr />
                  <div class="text-center">
                    <button type="submit" id="delete-golfcard" class="btn btn-danger btn-fill btn-wd btn-clean">Eyða</button>
                    <button type="submit" onclick="$('#cardinfo').modal('toggle');" class="btn btn-warning btn-fill btn-wd btn-clean">Loka</button>
                  </div>
              </div>
          </div>
        </div>
    </div>
  </div>
</div>

  {% endblock %}

app/templates/main/_sidebar.html
{% block _sidebar %}
<div class="sidebar" data-background-color="white" data-active-color="danger">

<!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

  <div class="sidebar-wrapper">
        <div class="logo">
            <a href="http://www.fuglar.com" class="simple-text">
                Golfkort Fugla
            </a>
        </div>

        <ul class="nav">
            {% if request.path == '/' %}
            <li class="active">
            {% else %}
            <li>
            {% endif %}
                <a href="{{url_for('main.index')}}">
                    <i class="fa fa-calendar-minus-o"></i>
                    <p>Golfkort</p>
                </a>
            </li>

            {% if request.path == '/profile' %}
            <li class="active">
            {% else %}
            <li>
            {% endif %}
                <a href="{{url_for('main.profile')}}">
                    <i class="fa fa-user"></i>
                    <p>Notandasnið</p>
                </a>
            </li>

            {% if user.get_role() in ('admin', 'staff') %}
              {% if request.path == '/statistics' %}
              <li class="active">
              {% else %}
              <li>
              {% endif %}
                  <a href="{{url_for('main.statistics')}}">
                      <i class="fa fa-bar-chart"></i>
                      <p>Tölfræði</p>
                  </a>
              </li>
            {% endif %}

            {% if user.get_role() == 'admin' %}
              {% if companies %}
              {% for comp in companies %}
                {% if '/c/' in request.path and comp.name in request.path %}
                <li class="active">
                {% else %}
                <li>
                {% endif %}
                    <a href="{{url_for('main.company', name=comp.name)}}">
                        <i class="fa fa-users "></i>
                        <p>{{comp.name}}</p>
                    </a>
                </li>
              {% endfor %}
              {% endif %}

            {% endif %}


            <li>
                <a href="{{url_for('auth.logout')}}">
                    <i class="fa fa-key"></i>
                    <p>Útskrá</p>
                </a>
            </li>


        </ul>
  </div>
</div>

{% endblock %}

app/templates/main/index.html
{% extends "main/_base.html" %}
{% block main %}
<div class="row">
    <div class="col-lg-10 col-md-12">
        <div class="card">
            <div id="calendar"></div>
        </div>
    </div>
    <div class="col-lg-2 col-md-0">
        <div class="card" style='padding-bottom: 10px;'>
            <div class="header">
                <h4 class="title" style='padding-bottom: 5px;'>skráningarreglur</h4>
                <ol style='padding-left: 20px;'>
                  <li>Aðeins er hægt að skrá sig á kort frá einum golfvelli í einu, annaðhvort frá GR eða GKG.</li>
                  <li>Hægt er að skrá sig á kort fram í tímann, en aðeins á einum degi í einu (hvítu reitirnir), þar til hámarksfjölda korta er náð*.</li>
                  <li>*Það er alltaf hægt að taka frá kort samdægurs (græni reiturinn), sama hvort þú ert skráð/ur fyrir kortum fram í tímann, eða hámarksfjölda korta er náð.</li>
                </ol>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block head_js %}
  {% assets "calendar_js" %}
       <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

app/templates/main/profile.html
{% extends "main/_base.html" %}
{% block main %}

<div>
    <div class="row">

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="header">
                    <h4 class="title">Upplýsingar um notanda</h4>
                </div>
                <div class="content">
                    <form action="{{url_for('main.profile')}}" method="POST">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Fyrirtæki <span class="profile-info">(nafn á fyrirtækinu sem þú vinnur
                                            hjá)</span></label>
                                    <input type="text" class="form-control border-input input-clean" name="company"
                                        placeholder="Company" value="{{user.company}}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Stutt nafn <span class="profile-info">(nafn sem sést á golfkorti, hámark 10
                                            stafir)</span></label>
                                    <input type="text" class="form-control border-input input-clean" name="displayname"
                                        placeholder="Display name" value="{{user.displayname}}">
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-success btn-fill btn-wd btn-clean">Uppfæra upplýsingar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>

            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="header">
                    <h4 class="title">Skipta um lykilorð</h4>

                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-danger">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span><b> Villa - </b> {{ message }}</span>
                        </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
                <div class="content">
                    <form action="{{url_for('auth.change_password')}}" method="POST">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Núverandi lykilorð </label>
                                    <input class="form-control border-input input-clean" name="pw" type="password">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Nýtt lykilorð</label>
                                    <input class="form-control border-input input-clean" name="pw1" type="password">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Nýtt lykilorð aftur</label>
                                    <input class="form-control border-input input-clean" name="pw2" type="password">
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd btn-clean">Uppfæra lykilorð</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/main/statistics.html
{% extends "main/_base.html" %}
{% block main %}
<div class="row">

    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="header">
                <h4 class="title">Árið {{year}} er valið</h4>
            </div>

            <div class="content">

                <form action="{{url_for('main.statistics')}}" method="GET">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Veldu annað ár</label>
                                <select name="year">
                                    <option value="2023" {% if year=='2023' %} selected="selected" {% endif %}>2023
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd btn-clean">Sækja</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>

    
</div>
<div class="row">

    <div class="col-lg-6 col-sm-6">
        <div class="card">
            <div class="header">
                <h4 class="title">Notkun korta eftir mánuði</h4>
            </div>

            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <canvas id="usageChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-sm-6">
        <div class="card">
            <div class="header">
                <h4 class="title">Notkun korta eftir notendum</h4>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <canvas id="userUsageChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

{% block head_js %}
    <script type="text/javascript">
        $(document).ready(function () {

                bardata = {{ cardsused|safe }} ;
                userUsage = {{ cardsused_byuser|safe }} ;

                var ctx = document.getElementById('usageChart').getContext('2d');
                var chart = new Chart(ctx, {
                    // The type of chart we want to create
                    type: 'bar',

                    // The data for our dataset
                    data: {
                        labels: ['May', 'June', 'July', 'August', 'September'],
                        datasets: bardata.map(item => ({
                            label: item.shortname,
                            backgroundColor: item.color,
                            borderColor: item.color,
                            data: item.totals
                        })) 
                    },

                    // Configuration options go here
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });


                var uctx = document.getElementById('userUsageChart').getContext('2d');
                var chartUser = new Chart(uctx, {
                    // The type of chart we want to create
                    type: 'bar',

                    // The data for our dataset
                    data: {
                        labels: userUsage[0].names,
                        datasets: userUsage.map(item => ({
                            label: item.golfcourse_name,
                            backgroundColor: item.color,
                            borderColor: item.color,
                            data: item.totals
                        })) 
                    },

                    // Configuration options go here
                    options: {
                        scales: {
                            yAxes: [{
                                stacked: true,
                                ticks: {
                                    beginAtZero: true
                                }
                            }],
                            xAxes: [{
                                stacked: true,
                                ticks: {
                                    beginAtZero: true,
                                    maxRotation: 60,
                                    minRotation: 60
                                }
                            }]
                        }
                    }
                });
    });

    </script>
{% endblock %}