app/views/admin.py
import os
import random
import string

from datetime import datetime, date
from app import app
from sqlalchemy import exc

from flask import (
    render_template, request, redirect, url_for, json, Blueprint, session as flask_session
)
from flask_login import (
    current_user, login_required
)

from app.mail import send_mail
from app.decorators import requires_roles
from app.models import (
    SessionContext, IntegrityError, User, Company, Access, OAuth_User, QueryUnseenMessages,
    QueryUsers, Error,
    QueryError, QueryErrorWarning, GolfCourse, QueryGolfCourses, Card, QueryGolfCards
)


def get_random_alphaNumeric_string(stringLength=8):
    lettersAndDigits = string.ascii_letters + string.digits
    return ''.join((random.choice(lettersAndDigits) for i in range(stringLength)))



mod = Blueprint('admin', __name__, url_prefix='/admin')


@mod.route('/golfcourse_add/<name>', methods=["POST"])
@login_required
@requires_roles('admin')
def golfcourse_add(name):
    with SessionContext() as session:
        company = session.query(Company).filter_by(name=name).first()
        if not company:
            return redirect(url_for("main.index"))

        golfcourse = session.query(GolfCourse)\
            .filter_by(shortname=request.form.get("shortname"))\
            .filter_by(company_id=company.id).first()

        if not golfcourse:
            golfcourse = GolfCourse(name=request.form.get("name"),
                shortname=request.form.get("shortname"),
                color=request.form.get("color"),
                company_id=company.id)
        else:
            if request.form.get("name"):
                golfcourse.name = request.form.get("name")
            if request.form.get("color"):
                golfcourse.color = request.form.get("color")

        session.add(golfcourse)
        session.commit()

    return redirect(url_for("admin.admin", name=name))


@mod.route('/golfcourse_delete/<name>', methods=["POST"])
@login_required
@requires_roles('admin')
def golfcourse_delete(name):
    with SessionContext() as session:
        try:
            company = session.query(Company).filter_by(name=name).first()
            if not company:
                return redirect(url_for("main.index"))

            golfcourse = session.query(GolfCourse)\
                .filter_by(shortname=request.form.get("shortname"))\
                .filter_by(company_id=company.id).first()

            if golfcourse:

                session.delete(golfcourse)
                session.commit()
        except exc.IntegrityError as e:
            pass

    return redirect(url_for("admin.admin", name=name))


@mod.route('/golfcard_add/<name>', methods=["POST"])
@login_required
@requires_roles('admin')
def golfcard_add(name):
    with SessionContext() as session:
        try:
            company = session.query(Company).filter_by(name=name).first()
            if not company:
                return redirect(url_for("main.index"))

            golfcourse = session.query(GolfCourse)\
                .filter_by(shortname=request.form.get("shortname"))\
                .filter_by(company_id=company.id).first()

            if not golfcourse:
                return redirect(url_for("main.index"))

            golfcard = Card(company_id=company.id, golfcourse_id=golfcourse.id, number=request.form.get("number"))

            session.add(golfcard)
            session.commit()


        except Exception as e:
            pass

    return redirect(url_for("admin.admin", name=name))


@mod.route('/golfcard_delete/<name>', methods=["POST"])
@login_required
@requires_roles('admin')
def golfcard_delete(name):
    with SessionContext() as session:
        try:
            company = session.query(Company).filter_by(name=name).first()
            if not company:
                return redirect(url_for("main.index"))

            golfcourse = session.query(GolfCourse)\
                .filter_by(shortname=request.form.get("shortname"))\
                .filter_by(company_id=company.id).first()

            if not golfcourse:
                return redirect(url_for("main.index"))

            golfcard = session.query(Card).filter_by(company_id=company.id)\
                .filter_by(golfcourse_id=golfcourse.id)\
                .filter_by(number=request.form.get("number")).first()

            session.delete(golfcard)
            session.commit()


        except Exception as e:
            pass

    return redirect(url_for("admin.admin", name=name))




@mod.route("/reset_password", methods=["POST"])
@login_required
@requires_roles('admin')
def reset_password():

    user_id = request.form["user_id"]
    name = request.form["name"]
    email = request.form["email"]

    with SessionContext() as session:

        try:
            user = session.query(User)\
                .filter_by(id = user_id)\
                .filter_by(name = name)\
                .filter_by(email = email)\
                .first()
        except Exception:
            user = None

        if not user:
            return render_template("main/admin/password_reset.html", error="Notandi finnst ekki.", cards_left = 0)

        oauth = session.query(OAuth_User)\
            .filter_by(user_id = user.id)\
            .first()

        if oauth:
            return render_template("main/admin/password_reset.html", error="Notandi er skráður inn með facebook eða google.", cards_left = 0)


        password = get_random_alphaNumeric_string(40)
        user.update_password(password)
        session.add(user)
        session.commit()

        return render_template("main/admin/password_reset.html", user_id = user_id, name = name, email = email, password = password, cards_left = 0)




@mod.route("/update_card_count", methods=["POST"])
@login_required
@requires_roles('admin')
def update_card_count():

    user_id = request.form["user_id"]
    count = request.form["count"]

    with SessionContext() as session:

        try:
            user = session.query(User)\
                .filter_by(id = user_id)\
                .first()

            user.max_cards = int(count)
            session.add(user)
            session.commit()
        except Exception as e:
            print(str(e))

    return redirect(flask_session['url_admin_page'])

app/views/auth.py
import os
import random
import string

from datetime import datetime, date
from app import app, login_manager
from sqlalchemy import exc

from flask import (
    render_template, request, redirect, url_for, Blueprint, flash
)
from flask_login import (
    login_user, logout_user, current_user, login_required, fresh_login_required
)

from app.logging import logger, logg_error
from app.mail import send_mail
from app.oauth import OAuthSignIn
from app.models import (
    SessionContext, IntegrityError, User, Company, Access, OAuth_User, Error
)
from app.decorators import (
    validate_login, validate_registration, validate_provider,
    is_logged_in, requires_roles
)

mod = Blueprint('auth', __name__)


@mod.route('/login', methods=['GET', 'POST'])
@is_logged_in
@validate_login
def login():
    """ Loggs user in, if user exists this redirects to index
        otherwise it redirects back to login """

    if request.method == 'GET':
        return render_template("auth/login.html")

    with SessionContext(commit=True) as session:
        try:
            registerd_user = session.query(User)\
                                    .filter_by(email=request.form['email'])\
                                    .first()

            # If user does not exist, redirect to login with status message.
            if not registerd_user:
                logger.login_failed_user(request.form.get('email'))
                logg_error(location="login", error="Logged in with email that does not exist in database, {email}".format(email=request.form.get('email')), warning=True)
                return render_template("auth/login.html", status='user_does_not_exist')

            # If user password is incorrect, redirect to login with status message
            if not registerd_user.check_password(password=request.form.get('password')):
                logger.login_failed_password(request.form.get('email'))
                logg_error(location="login", error="Logged in with incorrect password {email}".format(email=request.form.get('email')), warning=True)
                return render_template("auth/login.html", status='wrong_password')

            remember_me = request.form.get('remember_me') is not None
            login_user(registerd_user, remember=remember_me)
            logger.login_successful(request.form.get('email'))
        except Exception as e:
            session.rollback()
            logg_error(location='login', error=str(e))
            return redirect(url_for('main.index'))

        return redirect(url_for('main.index'))


@mod.route('/register', methods=['GET', 'POST'])
@is_logged_in
@validate_registration
def register():
    """ Registers a user.
        Redirects to login """

    if request.method == 'GET':
        return render_template("auth/register.html")

    with SessionContext() as session:
        try:
            user = User(name=request.form['name'],
                        password=request.form['password'],
                        company=request.form['company'],
                        email=request.form['email'])

            session.add(user)
            session.commit()
        except exc.IntegrityError as e:
            session.rollback()
            logger.register_failed(request.form.get('email'))
            logg_error(location='register', error="Tried to register with email that already exists in database {email}".format(email=request.form.get('email')), warning=True)
            return render_template("auth/register.html",
                                   status='user_already_exists')
        except Exception as e:
            sesison.rollback()
            logg_error(location='register', error=str(e))
            return render_template("auth/register.html",
                                   status='error in registry')

        company = session.query(Company).filter_by(name='Fuglar').first()
        access = Access(user_id=user.id, company_id=company.id)
        session.add(access)
        session.commit()

        logger.register_successful(request.form.get('email'))
        send_mail(request.form['email'])
        login_user(user, remember=False)
        return redirect(url_for('auth.login'))


@mod.route('/authorize/<provider>')
@validate_provider
def oauth_authorize(provider):
    """ Used to call login provider """
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@mod.route('/callback/<provider>')
@validate_provider
def oauth_callback(provider):
    """ Loggs in a user if he exists, else it tries to register the user.
        Allways redirects to index """

    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))

    oauth = OAuthSignIn.get_provider(provider)
    id, email, name = oauth.callback()
    if email is None:
        logg_error(location='oauth_callback-{provider}'.format(provider=provider), error="No email supplied from provider, id: {id}, name: {name}".format(id=id, name=name))
        return redirect(url_for('main.index'))

    with SessionContext() as session:

        if provider == 'facebook':
            oauth_user = session.query(OAuth_User)\
                                .filter_by(provider_id=id, provider=provider)\
                                .first()
        else:
            oauth_user = session.query(OAuth_User)\
                                .filter_by(email=email, provider=provider)\
                                .first()


        print(oauth_user)

        if not oauth_user:
            try:
                objs = list()
                user = User(name=name,
                            password=''.join(random.choice(string.ascii_uppercase + string.digits + " ") for _ in range(100)),
                            company='',
                            email=email)
                session.add(user)
                session.commit()
                objs.append(user)
                oUser = OAuth_User(provider_id=id,
                                   user_id=user.get_id(),
                                   provider=provider,
                                   email=email)
                session.add(oUser)
                session.commit()
                objs.append(oUser)
                send_mail(id)
                logger.oauth_register_successful(email)

                company = session.query(Company).filter_by(name='Fuglar').first()
                access = Access(user_id=user.id, company_id=company.id)
                session.add(access)
                session.commit()
                objs.append(access)


            except Exception as e:
                logger.oauth_register_failed(email)
                session.rollback()
                logg_error(location='oauth_callback-{provider}'.format(provider=provider), error=str(e))
                try:
                    for ob in objs[::-1]:
                        session.delete(ob)
                        session.commit()
                except UnboundLocalError:
                    pass
                return redirect(url_for('main.index'))
        else:
            user = session.query(User).filter_by(id=oauth_user.user_id).first()
            logger.oauth_login_successful(email)


        login_user(user, remember=True)
        return redirect(url_for('main.index'))

'''
@app.route("/reauthenticate", methods=["GET", "POST"])
@login_required
def reauth():
    # if the session is `fresh` just redirect to the page the user has requested
    if not login_fresh():
        form = LoginForm()
        if form.validate_on_submit():
            # do password check here
            confirm_login()
            return redirect(url_for("index"))
        return render_template("reauth.html", form=form)
    return redirect(request.args.get("next") or url_for("index"))
'''


@mod.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))



@mod.route('/change_password', methods=['POST'])
@login_manager.needs_refresh_handler
def change_password():


    pw = request.form['pw']
    pw1 = request.form['pw1']
    pw2 = request.form['pw2']

    if pw1 != pw2:
        flash("Ný lykilorð passa ekki")
        return redirect(url_for('main.profile'))


    with SessionContext() as session:
        user = session.query(User)\
            .filter_by(id = current_user.id)\
            .first()

        if not user.check_password(pw):
            flash("Rangt lykilorð")
            return redirect(url_for('main.profile'))


        user.update_password(pw1)
        session.add(user)
        session.commit()  

        return redirect(url_for('main.index'))





""" REMEMBER
have
@login_manager.needs_refresh_handler
decorator in actions that are sensitive, like changing password
"""

app/templates/_base.html
<html>
    <head>
        {% assets "main_css" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}">
        {% endassets %}

        {% assets "main_js" %}
             <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% block head_js %}{% endblock %}


        {% include "_title.html" %}
    </head>

    <body>

      <div class="wrapper">

          {% block content %}{% endblock %}

      </div>

    </body>

    
    {% block modals %}{% endblock %}
</html>

app/templates/_footer.html
{% block _footer %}
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>

                <li>

                </li>
                <li>

                </li>
                <li>

                </li>
            </ul>
        </nav>
        <div class="copyright pull-right">
            v {{version}} - <script>document.write(new Date().getFullYear())</script></a>
        </div>
    </div>
</footer>
{% endblock %}

app/templates/_title.html
{% block _title %}
<link rel="icon" type="image/jpg" href="{{ url_for('static', filename='img/golf-ball.jpg') }}"/>
{% if title %}
  <title>{{ title }}</title>
{% else %}
  {% if language == "is" %}
    <title>Golfkort - Fuglar</title>
  {% else %}
    <title>Golftickets - Fuglar</title>
  {% endif %}
{% endif %}
{% endblock %}

app/templates/_topbar.html
{% block _topbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>

            <a class="navbar-brand" id="nav_name">{{user.name}}</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <!--
                    <a>
                        <i class="fa fa-bell"></i>
                        <p class="notification">{{cards_left}}</p>
                        <p>kort eftir</p>
                    </a>
                    -->
                </li>
            </ul>

        </div>
    </div>
</nav>

{% endblock %}

app/templates/admin.html
{% extends "base.html" %}
{% block content %}


<div class="row">


    <div class="col-md-6">
        <div class="card">
            <div class="header">
                <h4 class="title">Golfvellir</h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nafn</th>
                            <th>Stutt nafn</th>
                            <th>Litur</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for gc in golfcourses %}
                        <tr style="color: {{gc.color}};">
                          <td>{{gc.id}}</td>
                          <td>{{gc.name}}</td>
                          <td>{{gc.shortname}}</td>
                          <td>{{gc.color}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
            <div class="header">
                <h4 class="title">Bæta við golfvelli</h4>
            </div>
            <div class="content">
                <form action="{{url_for('admin.golfcourse_add', name=path)}}"  method="POST">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Nafn golfvallar</label>
                                <input type="text" class="form-control border-input" name="name">
                            </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Stutt nafn (einkvæmur til að uppfæra)</label>
                                <input type="text" class="form-control border-input" name="shortname">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Litir í hex</label>
                                <input type="text" class="form-control border-input" name="color">
                            </div>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-success btn-fill btn-wd">Uppfæra/Bæta við</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>


            <div class="header">
                <h4 class="title">Eyða golfvelli</h4>
            </div>
            <div class="content">
                <form action="{{url_for('admin.golfcourse_delete', name=path)}}"  method="POST">
                      <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Stutt nafn (einkvæmur til að uppfæra)</label>
                                <input type="text" class="form-control border-input" name="shortname">
                            </div>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-danger btn-fill btn-wd">Eyða</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
      </div>








      <div class="col-md-6">
          <div class="card">
              <div class="header">
                  <h4 class="title">Golfkort</h4>
              </div>
              <div class="content table-responsive table-full-width">
                  <table class="table table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                              <th>Stutt nafn</th>
                              <th>Numer</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for gca in golfcards %}
                          <tr style="color: {{gca.color}};">
                            <td>{{gca.id}}</td>
                            <td>{{gca.shortname}}</td>
                            <td>{{gca.number}}</td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>

              </div>
              <div class="header">
                  <h4 class="title">Bæta við golfkorti</h4>
              </div>
              <div class="content">
                  <form action="{{url_for('admin.golfcard_add', name=path)}}"  method="POST">
                        <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label>Stutt nafn golfvallar</label>
                                  <input type="text" class="form-control border-input" name="shortname" required>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label>Numer korts</label>
                                  <input type="text" class="form-control border-input" name="number" required>
                              </div>
                          </div>
                      </div>

                      <div class="text-center">
                          <button type="submit" class="btn btn-success btn-fill btn-wd">Uppfæra/Bæta við</button>
                      </div>
                      <div class="clearfix"></div>
                  </form>
              </div>


              <div class="header">
                  <h4 class="title">Eyða golfkorti</h4>
              </div>
              <div class="content">
                  <form action="{{url_for('admin.golfcard_delete', name=path)}}"  method="POST">
                    <div class="row">
                      <div class="col-md-6">
                          <div class="form-group">
                              <label>Stutt nafn golfvallar</label>
                              <input type="text" class="form-control border-input" name="shortname" required>
                          </div>
                      </div>
                      <div class="col-md-6">
                          <div class="form-group">
                              <label>Numer korts</label>
                              <input type="text" class="form-control border-input" name="number" required>
                          </div>
                      </div>
                  </div>

                      <div class="text-center">
                          <button type="submit" class="btn btn-danger btn-fill btn-wd">Eyða</button>
                      </div>
                      <div class="clearfix"></div>
                  </form>
              </div>
          </div>
        </div>







        <div class="col-md-6">
              <div class="card">
                  <div class="header">
                      <h4 class="title">User access table</h4>
                      <p class="category">Table shows what users have access to admin and statistic pages</p>
                  </div>
                  <div class="content table-responsive table-full-width">
                      <table class="table table-striped">
                          <thead>
                              <tr>
                                  <th>ID</th>
                                	<th>Email/provider_id</th>
                                	<th>Access</th>
                                	<th>Statistics</th>
                                	<th>Admin</th>
                              </tr>
                          </thead>
                          <tbody>
                              {% for u in users %}
                              <tr>
                                <td>{{u.id}}</td>
                                <td>{{u.email}}</td>
                                <td>{{u.company}}</td>
                                {% if u.role in (1, 0) %}
                                  <td>x</td>
                                {% else %}
                                  <td></td>
                                {% endif %}
                                {% if u.role == 0 %}
                                  <td>x</td>
                                {% else %}
                                  <td></td>
                                {% endif %}

                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>

                  </div>
              </div>
          </div>






    <div class="col-md-6">
          <div class="card">
              <div class="header">
                  <h4 class="title">Warning log</h4>
                  <p class="category">Table shows all warnings</p>
              </div>
              <div class="content table-responsive table-full-width">
                  <table class="table table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                            	<th>Location</th>
                            	<th>Date</th>
                            	<th>Message</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for ew in errorswarning %}
                          <tr>
                            <td>{{ew.id}}</td>
                            <td>{{ew.location}}</td>
                            <td>{{ew.date}}</td>
                            <td>{{ew.error_message}}</td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>

              </div>
          </div>
      </div>

      <div class="col-md-6">
            <div class="card">
                <div class="header">
                    <h4 class="title">Error log</h4>
                    <p class="category">Table shows all errors</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                              	<th>Location</th>
                              	<th>Date</th>
                              	<th>Message</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ew in errors %}
                            <tr>
                              <td>{{ew.id}}</td>
                              <td>{{ew.location}}</td>
                              <td>{{ew.date}}</td>
                              <td>{{ew.error_message}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>



</div>


{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-10 col-md-12">
        <div class="card">
            <div id="calendar"></div>
        </div>
    </div>
</div>

{% endblock %}

{% block head_js %}
  {% assets "calendar_js" %}
       <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}

app/templates/menu_left.html
{% block menu_left %}
<div class="sidebar" data-background-color="white" data-active-color="danger">

<!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

  <div class="sidebar-wrapper">
        <div class="logo">
            <a href="http://www.fuglar.com" class="simple-text">
                Golfkort Fugla
            </a>
        </div>

        <ul class="nav">
            {% if request.path == '/' %}
            <li class="active">
            {% else %}
            <li>
            {% endif %}
                <a href="{{url_for('index')}}">
                    <i class="fa fa-calendar-minus-o"></i>
                    <p>Golfkort</p>
                </a>
            </li>

            {% if request.path == '/profile' %}
            <li class="active">
            {% else %}
            <li>
            {% endif %}
                <a href="{{url_for('profile')}}">
                    <i class="fa fa-user"></i>
                    <p>Notandasnið</p>
                </a>
            </li>

            {% if user.get_role() in ('admin', 'staff') %}
              {% if request.path == '/statistics' %}
              <li class="active">
              {% else %}
              <li>
              {% endif %}
                  <a href="{{url_for('statistics')}}">
                      <i class="fa fa-bar-chart"></i>
                      <p>Tölfræði</p>
                  </a>
              </li>
            {% endif %}

            {% if user.get_role() == 'admin' %}
              {% for comp in companies %}
                {% if '/admin' in request.path and comp.name in request.path %}
                <li class="active">
                {% else %}
                <li>
                {% endif %}
                    <a href="{{url_for('admin.admin', name=comp.name)}}">
                        <i class="fa fa-users "></i>
                        <p>{{comp.name}}</p>
                    </a>
                </li>
              {% endfor %}

            {% endif %}


            <li>
                <a href="{{url_for('auth.logout')}}">
                    <i class="fa fa-key"></i>
                    <p>Útskrá</p>
                </a>
            </li>


        </ul>
  </div>
</div>

{% endblock %}